p_noise:    0.05

n_particles: 1000
p_lr:         0.001
p_gamma:      0.98
p_epsilon:    1
p_epsilon_decay:  0.999
p_epsilon_min:  0.1
p_buffer_size:  50000

seq_len:      20
d_lr:         1e-5
d_gamma:      0.98
d_epsilon:    1
d_epsilon_decay:  0.9995
d_epsilon_min:  0.01
d_buffer_size:  100000


num_eps:      5000
batch_size:   64
eval_freq:    50
eval_size:    30
max_steps:    300
warmup:       10

hydra:
  run:
    dir: .
  job:
    env_set:
      HYDRA_FULL_ERROR: "1"